Fix compilation error on unknown type name 'bool'
On OpenWRT build system I get the following error message if I update to
the new keepalived version 2.0.7:

----
process.c:41:8: error: unknown type name 'bool'
 static bool realtime_priority_set;
        ^~~~
process.c:49:8: error: unknown type name 'bool'
 static bool priority_set;
        ^~~~
----

Include the header <stdbool.h> in process.c will fix this issue.

Signed-off-by: Florian Eckert <fe@dev.tdt.de>